/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
'use strict';

systemDictionary = {
  'gree-hvac adapter settings': {
    "en": "Gree HVAC adapter settings",
    "de": "Gree HVAC Adapter Einstellungen",
    "ru": "Настройки адаптера Gree HVAC",
    "pt": "Configurações do adaptador de HVAC da Gree",
    "nl": "Gree HVAC-adapterinstellingen",
    "fr": "Paramètres de l'adaptateur Gree CVC",
    "it": "Impostazioni dell'adattatore Gree HVAC",
    "es": "Ajustes de adaptador HVAC Gree",
    "pl": "Ustawienia adaptera Gree HVAC",
    "uk": "Параметри адаптера Gree HVAC",
    "zh-cn": "Gree HVAC 适配器设置"
  },
  'devicelist': {
    "en": "Device IPs, delimited by semicolon",
    "de": "Geräte-IPs, begrenzt durch Semikolon",
    "ru": "Устройства IP-адреса, разделенные полуколоном",
    "pt": "IPs do dispositivo, delimitado por ponto e vírgula",
    "nl": "Apparaat IP's, afgebakend door puntkomma",
    "fr": "IP du périphérique, délimité par un point-virgule",
    "it": "Dispositivi IP, delimitati da semicolon",
    "es": "IPs de dispositivos, delimitados por semicolon",
    "pl": "Urządzenie IP, wyznaczone przez średnik",
    "uk": "IP пристроїв, розділені крапкою з зап'ятою",
    "zh-cn": "设备 IP, 用分号分隔"
  },
  'pollInterval': {
    "en": "Polling interval in milliseconds",
    "de": "Polierintervall in Millisekunden",
    "ru": "Интервал опроса в миллисекундах",
    "pt": "Intervalo de polimento em milissegundos",
    "nl": "Berekeninterval in milliseconden",
    "fr": "Intervalle de scrutin en millisecondes",
    "it": "Intervallo di inquinamento in millisecondi",
    "es": "Intervalo de votación en milisegundos",
    "pl": "Odstęp między badaniami w milisekundach",
    "uk": "Інтервал опитування в мілісекундах",
    "zh-cn": "投票间隔( 毫秒)"
  },
  'Gree-HVAC adapter': {
    "en": "Gree-HVAC adapter",
    "de": "Gree-HVAC-Adapter",
    "ru": "Адаптер Gree-HVAC",
    "pt": "Adaptador Gree-HVAC",
    "nl": "Gree-HVAC-adapter",
    "fr": "Adaptateur Gree-HVAC",
    "it": "Adattatore Gree-HVAC",
    "es": "Adaptador Gree-HVAC",
    "pl": "Adapter Gree-HVAC",
    "uk": "Адаптер Gree-HVAC",
    "zh-cn": "Gree-HVAC 适配器"
  },
  'Devices': {
    "en": "Devices",
    "de": "Geräte",
    "ru": "Устройства",
    "pt": "Dispositivos",
    "nl": "Apparaten",
    "fr": "Dispositifs",
    "it": "Dispositivi",
    "es": "Dispositivos",
    "pl": "Urządzenia",
    "uk": "Пристрої",
    "zh-cn": "设备"
  },
  'Settings': {
    "en": "Settings",
    "de": "Einstellungen",
    "ru": "Настройки",
    "pt": "Configurações",
    "nl": "Instellingen",
    "fr": "Paramètres",
    "it": "impostazioni",
    "es": "Configuraciones",
    "pl": "Ustawienia",
    "uk": "Налаштування",
    "zh-cn": "设定值"
  },
  'Rename device': {
    "en": "Rename device",
    "de": "Rename Gerät",
    "ru": "Переименовать устройство",
    "pt": "Renomear dispositivo",
    "nl": "Hernoem apparaat",
    "fr": "Renommer le périphérique",
    "it": "Rinominare dispositivo",
    "es": "Renombrado dispositivo",
    "pl": "Zmień nazwę urządzenia",
    "uk": "Перейменувати пристрій",
    "zh-cn": "重命名设备"
  },
  'Save': {
    "en": "Save",
    "de": "Speichern",
    "ru": "Сохранить",
    "pt": "Salvar",
    "nl": "Opslaan",
    "fr": "Enregistrer",
    "it": "Salva",
    "es": "Guardar",
    "pl": "Zapisz",
    "uk": "Зберегти",
    "zh-cn": "保存"
  },
  'Cancel': {
    "en": "Cancel",
    "de": "Abbrechen",
    "ru": "Отмена",
    "pt": "Cancelar",
    "nl": "Annuleren",
    "fr": "Annuler",
    "it": "Annulla",
    "es": "Cancelar",
    "pl": "Anuluj",
    "uk": "Відмінити",
    "zh-cn": "取消"
  },
  'Name': {
    "en": "Name",
    "de": "Name",
    "ru": "Имя",
    "pt": "Nome",
    "nl": "Naam",
    "fr": "Dénomination",
    "it": "Nome",
    "es": "Nombre",
    "pl": "Nazwa",
    "uk": "Ім'я",
    "zh-cn": "名称"
  },
  'Refresh devices': {
    "en": "Refresh devices",
    "de": "Kühlgeräte",
    "ru": "Обновить устройства",
    "pt": "Dispositivos de atualização",
    "nl": "Hulpmiddelen verversen",
    "fr": "Rénover les appareils",
    "it": "Dispositivi di raffreddamento",
    "es": "Dispositivos de referencia",
    "pl": "Urządzenia odświeżające",
    "uk": "Оновити пристрої",
    "zh-cn": "刷新设备"
  },
  "Edit device name": {
    "en": "Edit device name",
    "de": "Gerätename bearbeiten",
    "ru": "Изменить имя устройства",
    "pt": "Editar nome do dispositivo",
    "nl": "Apparaatnaam bewerken",
    "fr": "Modifier le nom du périphérique",
    "it": "Modifica nome dispositivo",
    "es": "Editar nombre del dispositivo",
    "pl": "Edytuj nazwę urządzenia",
    "uk": "Редагувати ім'я пристрою",
    "zh-cn": "编辑设备名称"
  },
  "Power On/Off": {
    "en": "Power On/Off",
    "de": "Ein/Aus",
    "ru": "Включение/выключение",
    "pt": "Ligar/Desligar",
    "nl": "Aan/Uit",
    "fr": "Marche/Arrêt",
    "it": "Accendi/Spegni",
    "es": "Encendido/Apagado",
    "pl": "Włącz/Wyłącz",
    "uk": "Увімкнути/вимкнути",
    "zh-cn": "开/关"
  },
  "Display On/Off": {
    "en": "Display On/Off",
    "de": "Display Ein/Aus",
    "ru": "Дисплей Вкл/Выкл",
    "pt": "Exibir Ligar/Desligar",
    "nl": "Display Aan/Uit",
    "fr": "Afficher Marche/Arrêt",
    "it": "Display Accendi/Spegni",
    "es": "Mostrar Encendido/Apagado",
    "pl": "Wyświetl Włącz/Wyłącz",
    "uk": "Дисплей Увімкнути/вимкнути",
    "zh-cn": "显示 开/关"
  },
  "Temperature unit": {
    "en": "Temperature unit",
    "de": "Temperatur Einheit",
    "ru": "Единица температуры",
    "pt": "Unidade de temperatura",
    "nl": "Temperatuureenheid",
    "fr": "Unité de température",
    "it": "Unità di temperatura",
    "es": "Unidad de temperatura",
    "pl": "Jednostka temperatury",
    "uk": "Одиниця температури",
    "zh-cn": "温度单位"
  },
  "Increase temperature": {
    "en": "Increase temperature",
    "de": "Temperatur erhöhen",
    "ru": "Увеличить температуру",
    "pt": "Aumentar temperatura",
    "nl": "Temperatuur verhogen",
    "fr": "Augmenter la température",
    "it": "Aumentare la temperatura",
    "es": "Aumentar la temperatura",
    "pl": "Zwiększ temperaturę",
    "uk": "Збільшити температуру",
    "zh-cn": "增加温度"
  },
  "Decrease temperature": {
    "en": "Decrease temperature",
    "de": "Temperatur senken",
    "ru": "Уменьшить температуру",
    "pt": "Diminuir temperatura",
    "nl": "Temperatuur verlagen",
    "fr": "Diminuer la température",
    "it": "Diminuisci la temperatura",
    "es": "Disminuir la temperatura",
    "pl": "Zmniejsz temperaturę",
    "uk": "Зменшити температуру",
    "zh-cn": "降低温度"
  },
  "Mode": {
    "en": "Mode",
    "de": "Modus",
    "ru": "Режим",
    "pt": "Modo",
    "nl": "Modus",
    "fr": "Mode",
    "it": "Modalità",
    "es": "Modo",
    "pl": "Tryb",
    "uk": "Режим",
    "zh-cn": "模式"
  },
  "Fan speed": {
    "en": "Fan speed",
    "de": "Lüftergeschwindigkeit",
    "ru": "Скорость вентилятора",
    "pt": "Velocidade do ventilador",
    "nl": "Ventilatorsnelheid",
    "fr": "Vitesse du ventilateur",
    "it": "Velocità della ventola",
    "es": "Velocidad del ventilador",
    "pl": "Prędkość wentylatora",
    "uk": "Швидкість вентилятора",
    "zh-cn": "风扇速度"
  },
  "Turbo On/Off": {
    "en": "Turbo On/Off",
    "de": "Turbo Ein/Aus",
    "ru": "Турбо Вкл/Выкл",
    "pt": "Turbo Ligar/Desligar",
    "nl": "Turbo Aan/Uit",
    "fr": "Turbo Marche/Arrêt",
    "it": "Turbo Accendi/Spegni",
    "es": "Turbo Encendido/Apagado",
    "pl": "Turbo Włącz/Wyłącz",
    "uk": "Турбо увімкнути/вимкнути",
    "zh-cn": "涡轮 开/关"
  }
};